version: '3'
services:
  minio:
    container_name: minio 
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minionetwork
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=root123456
      - MINIO_DEFAULT_BUCKETS=videos
  
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - redis
    volumes:
      - redis_volume_data:/data

  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo 
  
  noise:
    container_name: NOise
    image: shivani1is2docking/noise:latest
    ports:
      - '3010:3000'
    depends_on:
      - mongodb
      - redis

networks:
  minionetwork:
    driver: bridge
  redis:
    driver: bridge
  mongo:
    driver: bridge

volumes:
  minio_data:
  redis_volume_data:
  mongodb_data:
